using System.Numerics;
using Content.Client._ES.Stagehand.Ui;
using Content.Client._ES.Voting;
using Content.Client.UserInterface.Screens;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Shared._ES.Stagehand.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Screens;

[GenerateTypedNameReferences]
public sealed partial class StagehandGameScreen : InGameScreen
{
    [Dependency] private readonly IEntityManager _ent = default!;

    public const string StyleClassChatContainer = "ChatContainer";
    public const string StyleClassChatOutput = "ChatOutput";

    public StagehandGameScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(FullScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.CenterRight, margin: 10);

        ViewportContainer.OnResized += ResizeActionContainer;
    }

    protected override void OnLoaded()
    {
        UserInterfaceManager.GetUIController<StagehandObserveUIController>().Update(ObserveControl);
        UserInterfaceManager.GetUIController<StagehandVoteUIController>().Update(VoteControl);
        ObserveControl.OnWarpButtonPressed += OnWarpButtonPressed;
    }

    protected override void OnUnloaded()
    {
        base.OnUnloaded();

        ObserveControl.OnWarpButtonPressed -= OnWarpButtonPressed;
    }

    private void OnWarpButtonPressed(EntityUid mind)
    {
        _ent.RaisePredictiveEvent(new ESStagehandWarpMessage
        {
            Target = _ent.GetNetEntity(mind),
        });
    }

    private void ResizeActionContainer()
    {
        float indent = 20;
        Actions.ActionsContainer.MaxGridWidth = ViewportContainer.Size.X - indent;
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        ChatBox.MinSize = size;
    }
}
