- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelAdmin
    id: AdminPDA
  storage:
    back:
    - GasAnalyzer
    - trayScanner
    - AccessConfiguratorUniversal
    - Multitool
