using System.Linq;
using Content.Client._ES.Core;
using Content.Client._ES.Masks;
using Content.Client._ES.Objectives;
using Content.Client._ES.Objectives.Ui;
using Content.Client.Roles;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Auditions.Components;
using Content.Shared._ES.Masks;
using Content.Shared._ES.Objectives.Components;
using Content.Shared._ES.Stagehand.Components;
using Content.Shared.Mind;
using Content.Shared.Warps;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ES.Stagehand.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESStagehandObserveWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly JobSystem _job;
    private readonly ESMaskSystem _mask;
    private readonly ESObjectiveSystem _objective;

    public event Action<EntityUid>? OnWarpButtonPressed;

    public EntityUid? CurrentEntity;

    public ESStagehandObserveWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _job = _entityManager.System<JobSystem>();
        _mask = _entityManager.System<ESMaskSystem>();
        _objective = _entityManager.System<ESObjectiveSystem>();

        WarpButton.OnPressed += InvokeWarp;
    }

    protected override void Opened()
    {
        base.Opened();

        _mask.OnMaskChanged += OnMaskChanged;
        _objective.OnObjectivesChanged += OnObjectivesChanged;
    }

    public override void Close()
    {
        base.Close();

        _mask.OnMaskChanged -= OnMaskChanged;
        _objective.OnObjectivesChanged -= OnObjectivesChanged;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        _mask.OnMaskChanged -= OnMaskChanged;
        _objective.OnObjectivesChanged -= OnObjectivesChanged;
    }

    private void OnMaskChanged(EntityUid mind, ProtoId<ESMaskPrototype>? mask)
    {
        Update();
        UpdateInfoPanel();
    }

    private void OnObjectivesChanged(Entity<ESObjectiveHolderComponent> mind)
    {
        if (mind == CurrentEntity)
            UpdateInfoPanel();
    }

    public void Update()
    {
        MindsContainer.Children.Clear();

        var minds = new List<Entity<MindComponent, ESCharacterComponent>>();

        var query = _entityManager.EntityQueryEnumerator<ESCharacterComponent, MindComponent>();
        while (query.MoveNext(out var uid, out var character, out var mind))
        {
            if (mind.OriginalOwnerUserId is null)
                continue;

            minds.Add((uid, mind, character));
        }

        var warps = new List<EntityUid>();
        var warpQuery = _entityManager.EntityQueryEnumerator<ESStagehandAwareComponent, WarpPointComponent>();
        while (warpQuery.MoveNext(out var uid, out _, out _))
        {
            warps.Add(uid);
        }

        var orderedMinds = minds
            .OrderBy(m => _mask.GetTroupeOrNull((m, m.Comp1)))
            .ThenBy(m => m.Comp2.Name);

        var grp = new ButtonGroup();
        foreach (var mind in orderedMinds)
        {
            var button = new ESObservablePlayerButton
            {
                Group = grp,
            };
            button.SetPlayer(mind);
            button.OnPressed += _ =>
            {
                SetInfoPanel(mind);
            };
            MindsContainer.AddChild(button);
        }

        var orderedWarps = warps
            .OrderBy(e => _entityManager.GetComponent<MetaDataComponent>(e).EntityName);

        foreach (var warp in orderedWarps)
        {
            var button = new ESObservablePlayerButton();
            button.ToggleMode = false;
            button.SetEntity(warp);
            button.OnPressed += _ =>
            {
                OnWarpButtonPressed?.Invoke(warp);
            };
            MindsContainer.AddChild(button);
        }
    }

    public void UpdateInfoPanel()
    {
        if (!_entityManager.TryGetComponent<MindComponent>(CurrentEntity, out var mind) ||
            !_entityManager.TryGetComponent<ESCharacterComponent>(CurrentEntity, out var character))
            return;

        SetInfoPanel((CurrentEntity.Value, mind, character));
    }

    public void SetInfoPanel(Entity<MindComponent, ESCharacterComponent> ent)
    {
        if (_entityManager.Deleted(ent))
            return;

        PlayerInfoContainer.Visible = true;

        var (uid, mind, character) = ent;
        CurrentEntity = uid;
        WarpButton.Disabled = mind.CurrentEntity == null; // See ESStagehandSystem.cs

        var mask = _mask.GetMaskOrNull((uid, mind));
        var troupe = _mask.GetTroupeOrNull((uid, mind));

        NameLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-name-big", ("text", character.Name)));

        if (_job.MindTryGetJob(uid, out var job))
            JobLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-job", ("text", job.LocalizedName)));

        if (_prototype.TryIndex(mask, out var maskPrototype))
        {
            MaskLabel.UnsafeSetMarkup(
                Loc.GetString("es-observe-menu-label-name-big", ("text", Loc.GetString(maskPrototype.Name))),
                maskPrototype.Color);
        }

        if (_prototype.TryIndex(troupe, out var troupePrototype))
        {
            TroupeLabel.UnsafeSetMarkup(
                Loc.GetString("es-observe-menu-label-fmt", ("text", Loc.GetString(troupePrototype.Name))),
                troupePrototype.Color);
        }

        ObjectiveContainer.Children.Clear();
        foreach (var objective in _objective.GetObjectives(uid))
        {
            var ctrl = new ESObjectiveControl();
            ctrl.SetObjective(objective);
            ObjectiveContainer.AddChild(ctrl);
        }
    }

    private void InvokeWarp(BaseButton.ButtonEventArgs obj)
    {
        if (CurrentEntity.HasValue)
            OnWarpButtonPressed?.Invoke(CurrentEntity.Value);
    }
}

