using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Stagehand.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESStagehandObserveControl : UIWidget
{
    public EntityUid? CurrentEntity;

    public event Action<EntityUid>? OnWarpButtonPressed;

    public ESStagehandObserveControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WarpButton.OnPressed += InvokeWarp;
    }

    private void InvokeWarp(BaseButton.ButtonEventArgs obj)
    {
        if (CurrentEntity.HasValue)
            OnWarpButtonPressed?.Invoke(CurrentEntity.Value);
    }

    //??? why is this necessary idk why emo it like this
    public void InvokeWarpForEntity(EntityUid entity)
    {
        OnWarpButtonPressed?.Invoke(entity);
    }
}

