using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.UI;

[GenerateTypedNameReferences]
public sealed partial class PheemyZooWindow : FancyWindow
{
    public PheemyZooWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

