using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using Content.Client._ES.UI.Controls.Layout;
using Content.Client.Guidebook.Richtext;
using Content.Shared._ES.Masks;
using Content.Shared.Roles;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._ES.Guidebook.Controls;

/// <summary>
///     Renders a panel with a list of tips, sourced from a mask prototype, troupe prototype, job prototype,
///     or any combination of the three (which will just combine the tips together).
/// </summary>
/// <remarks>
///     Tips inserted in this way should also ideally be present in the main tips dataset.
/// </remarks>
[GenerateTypedNameReferences, UsedImplicitly]
public sealed partial class ESGuideTipsEmbed : VStack, IDocumentTag
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ILogManager _log = default!;

    private ISawmill _sawmill;

    public ESGuideTipsEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _log.GetSawmill("guidebook.tips");
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        HashSet<LocId> tips = new();
        if (args.TryGetValue("Mask", out var maskProto))
        {
            if (!_proto.TryIndex<ESMaskPrototype>(maskProto, out var mask))
            {
                _sawmill.Error($"Mask prototype passed to tips embed tag is invalid: {maskProto}");
                return false;
            }

            tips.UnionWith(mask.Tips.ToHashSet());
        }

        if (args.TryGetValue("Job", out var jobProto))
        {
            if (!_proto.TryIndex<JobPrototype>(jobProto, out var job))
            {
                _sawmill.Error($"Job prototype passed to tips embed tag is invalid: {jobProto}");
                return false;
            }

            tips.UnionWith(job.Tips.ToHashSet());
        }

        if (args.TryGetValue("Troupe", out var troupeProto))
        {
            if (!_proto.TryIndex<ESTroupePrototype>(troupeProto, out var troupe))
            {
                _sawmill.Error($"Troupe prototype passed to tips embed tag is invalid: {troupeProto}");
                return false;
            }

            tips.UnionWith(troupe.Tips.ToHashSet());
        }

        if (tips.Count <= 0)
        {
            // this is still valid
            control = this;
            Visible = false;
            return true;
        }

        TipsTitle.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("es-guidebook-tips-embed-title")), tagsAllowed: null);

        // im sure this is linqable with some string method but whatever
        var tipsSb = new StringBuilder();
        foreach (var tip in tips)
        {
            tipsSb.Append(Loc.GetString("es-guidebook-tips-embed-wrap", ("tip", Loc.GetString(tip))));
            tipsSb.AppendLine();
        }

        Tips.SetMessage(FormattedMessage.FromMarkupOrThrow(tipsSb.ToString()), tagsAllowed: null);
        control = this;
        return true;
    }
}
