using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client._ES.UI.Controls.Layout;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Shared._ES.Masks;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._ES.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class ESGuideMaskEmbed : VStack, IDocumentTag, IPrototypeRepresentationControl
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ILogManager _log = default!;

    private ISawmill _sawmill;

    public IPrototype? RepresentedPrototype { get; set; }

    public ESGuideMaskEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _log.GetSawmill("guidebook.mask");
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        if (!args.TryGetValue("Mask", out var proto))
        {
            _sawmill.Error("Mask embed tag is missing mask prototype argument");
            control = null;
            return false;
        }

        if (!_proto.TryIndex<ESMaskPrototype>(proto, out var mask))
        {
            _sawmill.Error($"Mask prototype passed to mask embed tag is invalid: {proto}");
            control = null;
            return false;
        }

        var nameMsg = FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("es-guidebook-mask-embed-name",
                ("color", mask.Color),
                ("name", Loc.GetString(mask.Name))));
        MaskName.SetMessage(nameMsg, tagsAllowed: null);

        var descMsg = FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("es-guidebook-mask-embed-description",
                ("description", Loc.GetString(mask.Description))));
        MaskDescription.SetMessage(descMsg, tagsAllowed: null);

        var jobsList = ContentLocalizationManager.FormatList(mask.ProhibitedJobs.Select(p => _proto.Index(p).LocalizedName).ToList());
        var prohibitedJobsMsg = FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("es-guidebook-mask-embed-prohibited-jobs", ("jobs", jobsList)));
        MaskProhibitedJobs.SetMessage(prohibitedJobsMsg, tagsAllowed: null);

        if (jobsList.Length == 0)
            MaskProhibitedJobs.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("es-guidebook-mask-embed-prohibited-jobs-none")), tagsAllowed: null);

        RepresentedPrototype = mask;
        control = this;
        return true;
    }
}
