using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using Content.Client._ES.UI.Controls.Layout;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Shared._ES.Masks;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._ES.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class ESGuideMaskTipsEmbed : VStack, IDocumentTag
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ILogManager _log = default!;

    private ISawmill _sawmill;

    public ESGuideMaskTipsEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _log.GetSawmill("guidebook.mask");
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        if (!args.TryGetValue("Mask", out var proto))
        {
            _sawmill.Error("Mask tips embed tag is missing mask prototype argument");
            control = null;
            return false;
        }

        if (!_proto.TryIndex<ESMaskPrototype>(proto, out var mask))
        {
            _sawmill.Error($"Mask prototype passed to mask tips embed tag is invalid: {proto}");
            control = null;
            return false;
        }

        if (mask.Tips.Count <= 0)
        {
            // no error msg, this is still valid
            control = null;
            return false;
        }

        MaskTipsTitle.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("es-guidebook-mask-tips-embed-title")), tagsAllowed: null);

        // im sure this is linqable with some string method but whatever
        var tipsSb = new StringBuilder();
        foreach (var tip in mask.Tips)
        {
            tipsSb.Append(Loc.GetString("es-guidebook-mask-tips-embed-wrap", ("tip", Loc.GetString(tip))));
            tipsSb.AppendLine();
        }
        MaskTips.SetMessage(FormattedMessage.FromMarkupOrThrow(tipsSb.ToString()), tagsAllowed: null);

        control = this;
        return true;
    }
}
