- type: job
  id: ESSecurityOfficer
  name: ESjob-name-security
  description: ESjob-description-security
  playTimeTracker: ESJobSecurityOfficer
  startingGear: ESSecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hop
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External

- type: startingGear
  id: ESSecurityOfficerGear
  equipment:
    shoes: ClothingShoesBootsBlack
    id: SecurityPDA
    gloves: ClothingHandsGlovesColorBlack
    ears: ClothingHeadsetSecurity
    jumpsuit: ClothingUniformJumpsuitSec
    outerClothing: ESClothingOuterArmorSecurity
    back: ClothingBackpackSecurity
  storage:
    back:
    - ESBoxSurvival
    - Flash

- type: chameleonOutfit
  id: ESSecurityOfficer
  job: ESSecurityOfficer
  hidden: false
