- type: job
  id: ESWarden
  name: ESjob-name-warden
  description: ESjob-description-warden
  playTimeTracker: ESJobWarden
  startingGear: ESWardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - GenpopEnter
  - GenpopLeave

- type: startingGear
  id: ESWardenGear
  equipment:
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    gloves: ClothingHandsGlovesColorBlack
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHatWarden
    belt: ClothingBeltSecurityFilled
    jumpsuit: ClothingUniformJumpsuitWarden
    outerClothing: ESClothingOuterCoatWarden
    back: ClothingBackpackSecurity
  storage:
    back:
    - ESBoxSurvival
    - Flash

- type: chameleonOutfit
  id: ESWarden
  job: ESWarden
  hidden: false
