# Base mob components that originate from ES.
- type: entity
  id: ESBaseMob
  abstract: true
  components:
  - type: ESInherentLight
  - type: ESViewcone
  - type: ESViewconeOccludable
  - type: ESHoldToFace
  - type: ESKillTracker
  - type: ESPainFlash

- type: entity
  id: ESBaseMobActions
  abstract: true
  components:
  - type: ActionGrant
    actions:
    - ESActionSprint
