name: Report an issue
description: For issues that are not related to any other issue form.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing an issue! Please keep in mind most of our design discussion is done on discord, so feature
        requests and design changes should be brought up there first.
  - type: textarea
    attributes:
      label: Description
      description: |
        Describe the issue you are facing here. Make sure to include as many details as you can.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: List the steps required to reproduce the issue, if you have them.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: If your issue was discovered in specific circumstances or needs extra clarification, you can put it here.
    validations:
      required: false

