using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Options;

[GenerateTypedNameReferences]
public sealed partial class ESOptionsMenu : FancyWindow
{
    public ESOptionsMenu()
    {
        RobustXamlLoader.Load(this);
    }
}

