using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESVotingManagerControl : UIWidget
{
    public List<Entity<ESVoteComponent>> LastVotes = new();

    public ESVotingManagerControl()
    {
        RobustXamlLoader.Load(this);
    }
}

